//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerRisk.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomerRisk.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer,Event,Participant,Stake,Win
        ///1,1,6,50,250
        ///2,1,3,5,0
        ///3,1,3,20,0
        ///4,1,6,200,1000
        ///1,2,1,20,60
        ///2,2,1,5,15
        ///3,2,2,50,0
        ///4,2,5,100,0
        ///5,2,3,20,0
        ///1,3,5,50,0
        ///2,3,5,10,0
        ///3,3,5,20,0
        ///4,3,5,100,0
        ///5,3,6,20,0
        ///6,3,1,50,500
        ///1,4,1,50,120
        ///2,4,5,10,0
        ///3,4,6,50,0 
        ///1,5,10,50,400
        ///2,5,7,10,0
        ///3,5,9,20,0
        ///4,5,9,200,0
        ///4,5,10,250,2000
        ///5,5,10,20,160
        ///6,5,10,50,400
        ///1,5,7,40,0
        ///1,6,4,40,160
        ///2,6,3,15,0
        ///3,6,4,50,0
        ///4,6,5,100,0
        ///4,6,4,120,480
        ///5,6,4,10,40
        ///2,7,8,10,0
        ///2,7,7,20,0
        ///3,7,3,50,300
        ///1,8,5,80,320
        ///5,8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Settled {
            get {
                return ResourceManager.GetString("Settled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer,Event,Participant,Stake,To Win
        ///1,11,4,50,500
        ///3,11,6,50,400
        ///4,11,7,300,1200
        ///5,11,2,20,80
        ///1,12,4,500,5000
        ///2,12,4,20,200
        ///3,12,1,50,400
        ///4,12,1,250,1000
        ///5,12,5,100,800
        ///6,12,3,50,400
        ///6,12,2,50,200
        ///1,13,3,50,200
        ///2,13,1,10,50
        ///3,13,9,40,400
        ///4,13,6,200,1000
        ///6,13,4,500,4000
        ///1,14,2,1000,8000
        ///2,14,5,15,60
        ///3,14,8,300,900
        ///4,14,5,200,800
        ///5,14,6,100,600
        ///6,14,6,50,400
        ///.
        /// </summary>
        internal static string Unsettled {
            get {
                return ResourceManager.GetString("Unsettled", resourceCulture);
            }
        }
    }
}
